/* Sound and vibration for the moments she is not looking at the screen:
   a rest ending, an interval switching from hard to easy.

   The tone is generated by the browser rather than played from a file — no
   audio asset to download, and it works with no connection. */

let ctx: AudioContext | null = null;

function audio(): AudioContext | null {
  try {
    if (!ctx) {
      const Ctor =
        window.AudioContext ??
        (window as unknown as { webkitAudioContext?: typeof AudioContext })
          .webkitAudioContext;
      if (!Ctor) return null;
      ctx = new Ctor();
    }
    // iOS suspends the context until a user gesture resumes it.
    if (ctx.state === 'suspended') void ctx.resume();
    return ctx;
  } catch {
    return null;
  }
}

/** Call once from a tap, so iOS allows sound later when nobody is touching
    the screen. Without this, the rest-over tone is silently dropped. */
export function primeAudio(): void {
  audio();
}

function tone(frequency: number, ms: number, gain = 0.15): void {
  const a = audio();
  if (!a) return;
  try {
    const osc = a.createOscillator();
    const vol = a.createGain();
    osc.type = 'sine';
    osc.frequency.value = frequency;
    vol.gain.value = gain;
    osc.connect(vol);
    vol.connect(a.destination);

    const now = a.currentTime;
    osc.start(now);
    // Fade out rather than cutting, which clicks.
    vol.gain.setValueAtTime(gain, now + ms / 1000 - 0.03);
    vol.gain.linearRampToValueAtTime(0, now + ms / 1000);
    osc.stop(now + ms / 1000);
  } catch {
    // Sound is a convenience, never a requirement. Fail silently.
  }
}

function buzz(pattern: number | number[]): void {
  try {
    navigator.vibrate?.(pattern);
  } catch {
    /* not supported — fine */
  }
}

/** Rest is over, get back to it. */
export function cueRestOver(enabled: boolean): void {
  if (!enabled) return;
  tone(660, 140);
  window.setTimeout(() => tone(880, 200), 160);
  buzz([120, 80, 200]);
}

/** An interval is switching to the hard part. */
export function cueHard(enabled: boolean): void {
  if (!enabled) return;
  tone(880, 220, 0.18);
  buzz([220]);
}

/** An interval is switching to the easy part. */
export function cueEasy(enabled: boolean): void {
  if (!enabled) return;
  tone(440, 180);
  buzz([90]);
}

/** The session is finished. */
export function cueDone(enabled: boolean): void {
  if (!enabled) return;
  tone(523, 160);
  window.setTimeout(() => tone(659, 160), 170);
  window.setTimeout(() => tone(784, 300), 340);
  buzz([100, 60, 100, 60, 220]);
}
